//  This file was generated by CSLA Object Generator - CslaGenFork v4.5
//
// Filename:    DocTypeEditColl
// ObjectType:  DocTypeEditColl
// CSLAType:    EditableRootCollection

using System;
using Csla;

namespace BoundControls.Business
{
    public partial class DocTypeEditColl
    {

        #region OnDeserialized actions

        /*/// <summary>
        /// This method is called on a newly deserialized object
        /// after deserialization is complete.
        /// </summary>
        protected override void OnDeserialized()
        {
            base.OnDeserialized();
            // add your custom OnDeserialized actions here.
        }*/

        #endregion

        #region Pseudo Event Handlers

        //partial void OnFetchPre(DataPortalHookArgs args)
        //{
        //    throw new System.Exception("The method or operation is not implemented.");
        //}

        //partial void OnFetchPost(DataPortalHookArgs args)
        //{
        //    throw new System.Exception("The method or operation is not implemented.");
        //}

        #endregion

    }
}
